services:
  - type: web
    name: ia-extractor
    runtime: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: true
