services:
  - type: web
    name: ia-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
